name: tests

on:
  push:
  pull_request:

permissions: read-all

jobs:
  test:
    name: tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup PHP, with composer and extensions
        uses: shivammathur/setup-php@v2 #https://github.com/shivammathur/setup-php
        with:
          php-version: 8.4
          extensions: mbstring
          coverage: xdebug
      - name: Install Composer dependencies
        run: composer install -q
      - name: Setup Laravel environment
        run: cp .env.example .env && php artisan key:generate
      - name: Test
        run: vendor/bin/phpunit
      - name: Code Coverage
        uses: qltysh/qlty-action/coverage@v1
        with:
          token: ${{ secrets.QLTY_COVERAGE_TOKEN }}
          files: build/logs/clover.xml
