name: update

on:
  workflow_dispatch:
  schedule:
    - cron: '0 4 * * *' #UTC

jobs:
  composer:
    uses: kawax/composer-workflow/.github/workflows/update.yml@4bd02057ba6da0db59f49a8daa8c6d2d19bf240a # v1
    secrets:
      token: ${{ secrets.GITHUB_TOKEN }}
    with:
      php: latest
  npm:
    uses: kawax/npm-workflow/.github/workflows/update.yml@0340b8e7582f60e440c100abca8c306ddf221fda # v1
    secrets:
      token: ${{ secrets.GITHUB_TOKEN }}
